version: '2.4'
services:
  db:
    # image: datajoint/mysql:5.6
    image: datajoint/mysql:5.7
    # image: datajoint/mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    volumes:
      # persist data across docker-compose up/down
      - ./data:/var/lib/mysql
      # modify the my.cnf values
      - ./my.cnf:/etc/mysql/my.cnf
